### ISSUE TITLE
Auto switch between dark and light theme

### ISSUE THREAD

**Issue by evillalobosa** [lucas-labs/gitea-lugit-theme#1]
Hello.

First of all, thank you for your work. I think your theme is really beautiful

Second, I've been looking for how to automatically change the theme from light to dark, and I think I've found something interesting.

Although I could make a pull request on this, I'd like to let you know first.

I found the code of the [auto theme](https://github.com/go-gitea/gitea/blob/main/web_src/css/themes/theme-gitea-auto.css)
And I tried to apply the same.

So i create a `theme-auto-lugit.css` (in `public/assets/css`) with:

```css
@import "./theme-light.css" (prefers-color-scheme: light);
@import "./theme-dark.css" (prefers-color-scheme: dark);
```

And at least it works for me.

I think it would be cool if you could add this as well

**Comment by lucas-labs** [comment]
That's actually a great idea!

I would probably create a third theme file called "auto.scss" [here](https://github.com/lucas-labs/gitea-lugit-theme/tree/master/src/themes/scss). So that we can keep all "3" themes as an option (dark, light, auto).

I'll look into it tomorrow.

Thanks for the idea! Cheers!

**Comment by lucas-labs** [comment]
Thanks for the idea! Done!

Cheers
